services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - frontend-build:/usr/share/nginx/html:ro

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres-data:
  frontend-build:
