"""add order column to department

Revision ID: 1e5544e7791c
Revises: 2a1847e1055d
Create Date: 2025-04-28 17:12:10.977887

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e5544e7791c"
down_revision: Union[str, None] = "2a1847e1055d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "department",
        sa.Column("order", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index(op.f("ix_department_order"), "department", ["order"], unique=False)
    op.create_foreign_key(
        None,
        "staff",
        "department",
        ["department_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "staff", type_="foreignkey")
    op.drop_index(op.f("ix_department_order"), table_name="department")
    op.drop_column("department", "order")
    # ### end Alembic commands ###
